import React from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const HeroSection = dynamic(() => import('../components/Homepage/HeroSection'));
const TrendingSection = dynamic(() => import('../components/Homepage/TrendingSection'));
const InfoSection = dynamic(() => import('../components/Homepage/InfoSection'));
const ProductSection = dynamic(() => import('../components/Homepage/ProductSection'));
const Banner = dynamic(() => import('../components/Homepage/Banner'));
const TestimonySection = dynamic(() => import('../components/Homepage/TestimonySection'));
const PolicySection = dynamic(() => import('../components/Homepage/PolicySection'));

import withBaseLayout from '../components/Layout/BaseLayout';
import { projectName } from '../constant/projectSetting';

const Home=()=> {
  return (
    <React.Fragment>
      <Head>
        <title>{projectName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <HeroSection />
        <TrendingSection />
        <InfoSection />
        <ProductSection />
        <Banner />
        <TestimonySection />
        <PolicySection />
    </React.Fragment>
  )
}

const HOCprops ={
  displayName : "Home",
  fixedNavbar: false,
};
export default withBaseLayout(Home, HOCprops); 
